[build]
  base = "/"
  command = """
    yarn install --frozen-lockfile --legacy-peer-deps &&
    cd packages/twenty-shared && yarn build &&
    cd ../twenty-front && yarn build
  """
  publish = "packages/twenty-front/build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"
  VITE_DISABLE_TYPESCRIPT_CHECKER = "true"
  VITE_DISABLE_ESLINT_CHECKER = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "development"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 