[build]
  base = "/"
  command = """
    yarn install &&
    yarn workspace twenty-shared build &&
    yarn workspace twenty-front build
  """
  publish = "packages/twenty-front/build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "4.0.2"
  VITE_DISABLE_TYPESCRIPT_CHECKER = "true"
  VITE_DISABLE_ESLINT_CHECKER = "true"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "development"
  YARN_ENABLE_IMMUTABLE_INSTALLS = "false"
  YARN_ENABLE_GLOBAL_CACHE = "false"
  YARN_ENABLE_MIRROR = "false"
  YARN_NODE_LINKER = "node-modules"
  YARN_NM_MODE = "hardlinks-local"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 